rly_file = "Merseyrail.rly"
ttb_files = [ "Merseyrail.ttb",]
img_files = [ "GB-Merseyrail-Railway.bmp", "GB-Merseyrail-Railway-Preferred-Directions.bmp", "GB-Merseyrail-Railway-Grid.bmp",]
doc_files = [ "README.md",]
release_date = "2022-05-14"
version = "1.0.0"
country_code = "GB"
factual = true
description = ""
display_name = "Merseyrail"
name = "Merseyrail"
author = "mathstrains21"
contributors = []
