rly_file = "Merseyrail.rly"
ttb_files = [ "Merseyrail.ttb",]
img_files = [ "GB-Merseyrail-Railway.bmp", "GB-Merseyrail-Railway-Preferred-Directions.bmp", "GB-Merseyrail-Railway-Grid.bmp",]
doc_files = [ "MerseyrailNotes.md", "MerseyrailNotes.pdf",]
release_date = "2022-11-20"
version = "1.0.0"
country_code = "GB"
factual = true
description = "The Merseyrail Network controlled by Sandhills IECC and a few PSB's."
display_name = "Merseyrail"
name = "Merseyrail"
author = "mathstrains19"
contributors = []
ssn_files = [ "MerseyrailInitialSession.ssn",]
year = "2022"
difficulty = "3"
signal_position = "left"
